.TH gtkmenuplus 5 "2018-09-16" "version 1.1.8" "menu configuration file"
.SH NAME

Format of menu configuration files for gtkmenuplus(1).
.SH SYNOPSIS
.RS
.nf
\fC
menu_configuration_file

\fR
.fi
.RE
.SH DESCRIPTION

Gtkmenuplus takes a \fCmenu_configuration_file\fR as its primary argument, and
constructs a menu from the directives that it reads in the file.  This document
describes the format of the menu configuration file, and the set of valid
directives.
.SH FORMAT
.SS
Comments

Anything on a line after the "#" character is considered a comment and is
ignored, - "#" included.

The following cases are exceptions in which "#" and the characters that follow
it till the end of the line aren't comments:
.RS
.IP \[bu] 3
directives \fCcmd=\fR, \fCif=\fR, \fCelseif=\fR
.IP \[bu] 3
variable evaluation \fCvariable_name==\fR
.IP \[bu] 3
variable assignment of quoted strings that include #, such as quoted HTML
colors, i.e., "#FAF090"
.IP \[bu] 3
valid shell syntax following the above directives, i.e.,
\fCif=test ${y#prefix} = abc\fR
.RE

Any line whose first non-whitespace character is a "#" is ignored.
.SS
Lines

Blank lines are ignored.

Each meaningful line in a menu configuration file contains a directive (which
may be preceded by whitespace).  The case of directives is ignored.
.SS
Directives

Seven directives are inherited from myGtkMenu, the ancestor to gtkmenuplus.
\fB(M)\fR marks directives whose behaviour in gtkmenuplus differs from that in
myGtkMenu.
.RS
.nf
\fC
item=item_description
cmd=command                (M) (command may be null)
icon=path_to_image_file    (M) (path may be null)
separator
submenu=submenu_description
iconsize=size
menupos=x y                (M)
menuposition=x y           (synonym for menupos)

\fR
.fi
.RE

The remaining directives are new in gtkmenuplus:
.RS
.nf
\fC
icondirectory=path_to_icon_directory

format=format_string

tooltip=tooltip_text
tooltipformat=format_string

launcher=path_to_launcher(s)
launchersub=path_to_directory
launcherdirectory=path_to_launcher_directory
launcherdir=path_to_launcher_directory (synonym for launcherdirectory)
launcherargs=arguments
launcherdirfile=launcher_dirfile
launchersubmenu=launcher_dirfile

activationlogfile=logfile_path

include=menu_configuration_file or
include=path_to_directory[/file_glob] [directory_glob] 

if=condition
elseif=condition or elif=condition
else
endif or fi

error=message

/path_to/file
~/path_to/file

configure=option_list
onexit
endsubmenu

\fR
.fi
.RE

\fBNotes\fR

For \fCdirective=value\fR there may be whitespace between \fCdirective\fR and "=".
Whitespace between "=" and \fCvalue\fR is ignored, as is trailing whitespace after
\fCvalue\fR.

A line of \fCitem=\fR may be followed by a line of \fCcmd=\fR, \fCicon=\fR and/or
\fCtooltip=\fR, in any order.
.SS
Variables
.RS
.nf
\fC
variable_name=value
variable_name==expression

\fR
.fi
.RE

Any string preceding "=", aside from the directives listed above, will be taken
to be a declaration of a variable, providing it meets the following conditions.

A \fCvariable_name\fR may not be the same as any existing environmental variable.

A \fCvariable_name\fR must begin with an alphabetic character.  All other
characters in a \fCvariable_name\fR must be alphabetic, numeric or the underscore.

Whitespace between a \fCvariable_name\fR and "=" is ignored.

Whitespace following the "=", and trailing whitespace after \fCvalue\fR or
\fCexpression\fR is ignored.  If you want to include leading or trailing whitespace
in a value or expression, enclose it all in single or double quotes, which will
be stripped before the value is stored or the expression is evaluated.  You can
also use quotes if you want a value beginning with "=", e.g.
.RS
.nf
\fC
myvar="  something nice "

\fR
.fi
.RE

If a \fCvariable_name\fR is followed by "==", the text after the "==" is
interpreted as an expression which is passed to the shell for evaluation;
whatever ends up in stdout becomes the variable value.

The value of a \fCvariable_name\fR is referenced as \fC$variable_name\fR in \fIany\fR
subsequent line of the same file as well as of included files. For instance
\fC$variable_name\fR can be all or part of a command (in a \fCcmd=\fR line); of a menu
item's \fCitem_description\fR (in an \fCitem=\fR line); or of the condition on \fCif=\fR or
\fCelseif=\fR lines.

If the same \fCvariable_name\fR is re-assigned, including in included files, its
value is redefined.
.SS
Parameters

Additional arguments can optionally follow \fCmenu_configuration_file\fR on the
gtkmenuplus command line.  Such arguments are called \fIpositional parameters\fR,
and their value can be referenced by \fC$1\fR, \fC$2\fR,... etc, in any line in the
\fCmenu_configuration_file\fR (except \fCcmd=\fR lines, since \fC$1\fR, \fC$2\fR... may occur
in shell one-liners and be confused with gtkmenuplus command line parameter
references).

Referencing an unassigned (null) parameter is allowed in an evaluation context,
such as \fCif=\fR, \fCelseif=\fR or \fCvariable_name==\fR, and produces the value 0
('false', 'no').

\fC$0\fR references the \fCmenu_configuration_file\fR itself unless gtkmenuplus gets
its input from stdin.  Reference \fC$0\fR is invalid in included files.
.SS
Paths

The following lines may contain a path or paths:
.RS
.nf
\fC
cmd=command                
icondirectory=path_to_icon_directory
icon=path_to_image_file    
launcherdirectory=path_to_launcher_directory
launcher=path_to_launcher(s)
launchersub=path_to_directory
include=menu_configuration_file 
include=path_to_directory 

\fR
.fi
.RE

Paths may be absolute (beginning with "/") or relative.  They may begin with
the tilde ("~"), which in all cases will be expanded into \fC$HOME\fR, as it would
be by the shell.

Relative paths may begin with "./" and/or include "../", begin with the name of
a directory or simply name a file.  With some expections noted below, such
paths will be taken to be relative to the path of the directory that contains
the menu configuration file as specified on the gtkmenuplus command line.

\fBNote\fR Unlike what the shell does, gtkmenuplus resolves relative paths from
the path of the directory that contains \fC$0\fR rather than from the current
working directory.  This can be confusing. For that reason it is recommended to
invoke gtkmenplus with the full path of the \fCmenu_configuration_file\fR.  This
note applies to the remainder of this section.

\fBExceptions\fR the following directives resolve relative paths as noted:
.RS
.nf
\fC
icon=         directory in the last non\-null icondirectory= line, if any
launcher=     directory in the last non\-null launcherdirectory= line, if any
launchersub=  directory in the last non\-null launcherdirectory= line, if any
cmd=          assumed to be on the system's PATH.

\fR
.fi
.RE

The command on a \fCcmd=command\fR line in particular may contain multiple paths
requiring expansion (typically multiple arguments to the specified executable).
After expansion the entire command must be no longer than 1024 (?) characters.
.SH DIRECTIVES
.SS
Item
.RS
.nf
\fC
item=item_description

\fR
.fi
.RE

Denotes the \fCitem_description\fR to show in the menu. An underscore as part of
item description indicates that the following letter is the mnemonic (the
keyboard accelerator) for the menu item.

A mnemonic can also be added via global formatting, cf. \fCformat=\fR.

If you want to include an underscore in the item description but not use it to
indicate a mnemonic, use two consecutive underscores.

An \fCitem=\fR line may be immediately followed by any or all of \fCcmd=\fR, \fCicon=\fR
and \fCtooltip=\fR lines, in any order.

An \fCitem=\fR line marks the end of any menu item or submenu preceding it.
.SS
Cmd
.RS
.nf
\fC
cmd=command

\fR
.fi
.RE

Optional.  Denotes the command to run.

Must be preceded by an \fCitem=\fR line, and possibly by \fCicon=\fR or \fCtooltip=\fR
lines.  It applies to the menu entry begun by the preceding \fCitem=\fR line.

The command that follows \fCcmd=\fR on the line must be a valid (syntax error free)
shell command, or nothing.

\fCcmd=\fR, on its own, or an \fCitem=\fR not followed by a \fCcmd=\fR, will create a
disabled menu item (possibly to use as a menu or section title).

You can use "~" to refer to your home directory, e.g. ~/bin/myScript.sh.

A \fCcmd=\fR line is the only kind of line in which you can't use parameters
originating on the gtkmenuplus command line, or as part of an include line,
since \fC$1\fR, \fC$2\fR... may occur in shell one-liners and be confused with
gtkmenuplus command line parameter references.  If you want to use a parameter
in a command, set a variable to the parameter e.g.
.RS
.nf
\fC
myParam=$1

\fR
.fi
.RE

and use the variable ($myParam) in the command.


Not everything that can work at a shell prompt will work in \fCcmd=\fR:

.RS
.IP \[bu] 3
You can't specify more than one command on a line (using ;, && or |).
.IP \[bu] 3
You can't use environmental variables (e.g. $WINEPREFIX, $HOME).
.RE

However, you \fIcan\fR get the shell to do stuff like that for gtkmenuplus.  Either
you can make a small script containing the commands you need, or you can make
your command a shell invocation with \fCsh -c\fR, e.g.:
.RS
.nf
\fC
 # start two instances of freecell
 cmd=sh \-l \-c "( sol \-\-freecell &) ; (sol \-\-freecell &)"

\fR
.fi
.RE

You also can have:
.RS
.nf
\fC
 cmd=path_to_a_non_executable_file [path_to_other_non_executable_file ...]

\fR
.fi
.RE

A \fCnon_executable_file\fR could for instance be a doc, html, xls or plain text
file.  \fCpath_to_a_non_executable_file\fR can begin with a tilde (for the home
directory), or be a relative or absolute path.

If a \fCcmd=\fR begins with a \fCnon_executable_file\fR, its MIME type is used to
determine which application will be used to execute that file (and any
\fCpath_to_other_non_executable_files\fR on the same line).
.SS
Tooltip
.RS
.nf
\fC
tooltip=tooltip_text

\fR
.fi
.RE

Optional. Adds a tooltip to a menu item or submenu.

Must be preceded by an \fCitem=\fR, and possibly by an \fCicon=\fR and/or (if there's a
preceding \fCitem=\fR line) a \fCcmd=\fR line.  It applies to the menu entry begun by
the preceding \fCitem=\fR line or submenu begun by the preceding \fCsubmenu=\fR line.
.SS
Icon
.RS
.nf
\fC
icon=path_to_image_file | icon_name | NULL

\fR
.fi
.RE

Optional.  Denotes an image to show with the menu item or submenu.

Must be preceded by an \fCitem=\fR, or \fCsubmenu=\fR line, and possibly by an \fCicon=\fR
and/or (if there's a preceding \fCitem=\fR line) a \fCcmd=\fR line.

It applies to the menu entry begun by the preceding \fCitem=\fR line or submenu
begun by the preceding \fCsubmenu=\fR line.

If a menu item lacks an icon line, or has an \fCicon=\fR line with nothing
following the "=" sign, gtkmenuplus will attempt to find an icon associated
with the executable named in the menu item's \fCcmd=\fR line; or, if the \fCcmd=\fR
line specifies only a non-executable file, an attempt will be made to locate an
icon associated with the default program used to open that file.

There are situations in which gtkmenplus can't automatically determine the icon
image for an \fCitem=\fR without an \fCicon=\fR. In such cases you need specify the
icon explicitly:
.RS
.IP \[bu] 3
any submenu
.IP \[bu] 3
a menu item where the command on the \fCcmd=command\fR involves \fCsh -c\fR to run
multiple shell commands
.IP \[bu] 3
a menu item where \fCcmd=\fR involves a terminal emulator to run a shell command
.IP \[bu] 3
a menu item where \fCcmd=\fR involves gtksu, gksudo or equivalent to run a shell
command
.IP \[bu] 3
successive menu items (e.g. ones opening text files) which, based on command
or file type would all have the same icon
.IP \[bu] 3
a \fCcmd=\fR consisting of a URL to something on the net or on another machine.
If the net isn't accessible, gtkmenuplus will block while trying to get
information about the target file type.  It might be better to use a named
icon like, .e.g., text-html or applications-internet.
.RE

If you do not want an image on your menu item, use the line \fCicon=NULL\fR, or the
method described below.

If the most recently encountered "configure=" line in the menu configuration
file included the word \fCnoicons\fR, any item without an \fCicon=path_to_image_file\fR
or \fCicon=icon_name\fR line will not be assigned an image.

A subsequent \fCconfigure=\fR line containing the word \fCicons\fR will cause
gtkmenuplus to revert to its default behaviour of finding icons based on the
application or filetype specified on the \fCcmd=\fR line.

The \fCpath_to_image_file\fR includes a dotted file extension and follows the rules
for paths referred to in menu configuration files (see above):
.RS
.IP \[bu] 3
A \fCpath_to_image_file\fR can begin with a tilde, which will be expanded as in
bash to \fC$HOME\fR.
.IP \[bu] 3
It can be absolute.
.IP \[bu] 3
Or it can be relative.  If it doesn't begin with a dot, and the most recent
\fCicondirectory=path_to_icon_directory\fR line has a non-null
\fCpath_to_icon_directory\fR, the path is relative to that.  Otherwise it's
relative to the path in which the configuration file was found (as specified
on the gtkmenuplus command line, unless gtkmenuplus is reading from stdin).
.RE

The dotted file extension indicates one of the supported image types: png, svg,
xpm or gif.

Tip: To speed execution, all icon files associated with a menu configuration
file should be of the same image size.

Instead of a \fCpath_to_image_file\fR you can use an \fCicon_name\fR, which  is
distinguished by not including an extension for the image type.

An \fCicon_name\fR will be recognised if icons matching it are in one of the
standard sets of icon directories (e.g. /usr/share/pixmaps/, subdirectories of
/usr/share/icons, etc); in particular the icon names listed in
freedesktop.org's Icon Naming Specification:

http://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html
.SS
Format
.RS
.nf
\fC
format=formatting 

formatting=[ format_string [;|, format_string [;|, format_string... ]]]

\fR
.fi
.RE

Menu items and submenu labels following a \fCformat\fR line have the given
\fCformat_string\fR(s) applied, until the occurrence of the next
\fCformat=formatting\fR line.


If more than one \fCformat_string\fR occurs on a \fCformat=\fR line, each
\fCformat_string\fR is applied in turn to successive following items or submenu
labels at the same level as the menu level in which the \fCformat=\fR line occurs.
Items or submenu labels at any other level in the menu hierachy are \fInot\fR
subject to the \fCformat_string\fR sequence.

If \fCformatting\fR contains only one \fCformat_string\fR, that \fCformat_string\fR applies
to everything following, no matter where it is in the menu hierarchy.

A \fCformat_string\fR consists of a string of whitespace-separated
attribute="value" pairs, attributes and their values must be appropriate for
placement within a \fC<span>\fR tag in the Pango Text Attribute Markup Language,
see https://developer.gnome.org/pango/stable/PangoMarkupFormat.html for details
(the "convenience tags" mentioned aren't supported).

An additional non-Pango attribute="value" pair is supported, \fCmnemonic\fR, see
further down for details.

Examples:
.RS
.nf
\fC
format= font_desc="Sans Italic 12"
format= style="bold" underline="single"
format= foreground="blue"  # color names see /usr/share/X11/rgb.txt
format= weight="bold"      # also possible: "ultralight", "light", "normal",
                           # "ultrabold", "heavy", or a numeric weight
format= size='12800'       # in 1024ths of a point, or one of 'xx\-small',
                           # 'x\-small', # 'small', 'medium', 'large',
                           # 'x\-large', 'xx\-large'
format= color="RoyalBlue";color="DodgerBlue"  # alternate two shades

\fR
.fi
.RE

A \fCformat=\fR with a null \fCformat_string\fR causes all subsequent menu and submenu
items to revert to default formatting.

As well as using \fCformat=\fR lines to modify some menu and submenu entries,
global changes (background color, font, etc.) can be made to menus using the
built-in "GTK theme" mechanism.

GTK2 and GTK3 differ in the way themes are defined and applied for specific
applications. For GTK2 only you can invoke gtkmenuplus as such:
.RS
.nf
\fC
env GTK2_RC_FILES=gtk2_rc_file gtkmenuplus menu_configuration_file

\fR
.fi
.RE

Note: Since version 1.1.3 gtkmenplus unexports variable \fCGTK2_RC_FILES\fR to
avoid changing the default theme of any GTK2 application that is being
executed.

As yet another formatting method, the text of any menu item or submenu label
can be formatted by wrapping it in \fC<span format_string>some text</span>\fR tags,
e.g.
.RS
.nf
\fC
<span color="white">some text</span>

\fR
.fi
.RE

Menu items or submenus formatted by inclusion of \fC<span...>...</span>\fR tags or
by preceding \fCformat=\fR lines mustn't contain "<" or ">" characters.  Use
"\fC&lt;\fR"  or "\fC&gt;\fR" instead.

If a \fCformat=\fR line is in force, that will apply to all parts of a line
containing \fC<span...>...</span>\fR tags not within those tags.

\fCmnemonic=value\fR is a semantic, non-Pango attribute="value" that modifies each
formatted item label by inserting a keyboard accelerator key mark (\fC_\fR) before
the character that is to act as accelerator.  The key is detected only while
the menu is being displayed.  Menus display mnemonic keys as underlined
characters.

\fCValue\fR can be either \fC"1"\fR or an arbitrary non-null quoted string.
.RS
.IP \[bu] 3
\fC"1"\fR inserts \fC_\fR before the label, unless the label already includes its own
mnemonic.
.IP \[bu] 3
A quoted string inserts \fC_<char>\fR (notice the space) before the label, also
when then label already includes its own mnemonic. \fC<char>\fR represents a
character extracted (sequentially with recycling) from \fCvalue\fR The sequence is
recycled separately for each submenu level.
.RE

Examples:
.RS
.nf
\fC
format = mnemonic="1"
launchersub = /usr/share/applications

\fR
.fi
.RE

Turns the first letter of all application menu item labels into a mnemonic,
unless the label already includes its own mnemonic.
.RS
.nf
\fC
format = mnemonic="ABC"
submenu = England
  item = London
  item = Birmingham
  item = Liverpool
  item = Manchester
submenu = Scotland
  item = Glasgow
  item = Edingburgh
  item = Aberdeen
  item = Inverness

\fR
.fi
.RE

expands into two submenus with the following labels
.RS
.nf
\fC
_A England
   _A London, _B Birmingham, _C Liverpool, _A Manchester
_B Scotland
   _A Glasgow, _B Edingburgh, _C Aberdeen, _A Inverness

\fR
.fi
.RE

The rules for applying mnemonic="value" are the same rules as for applying
global label formatting.  menmonic="value" can't be used within \fC<span>\fR tags
and with directive \fCtooltipformat=\fR.
.SS
Tooltipformat
.RS
.nf
\fC
tooltipformat=format_string

\fR
.fi
.RE

The text of all tooltips encountered in menu items and submenus is formatted by
the preceding \fCtooltipformat=format_string\fR line.

\fCformat_string\fR is as for \fCformat=>format_string\fR lines.

A null \fCformat_string\fR turns off formatting for tooltips in subsequent menu
items and submenus.
.SS
Launcher
.RS
.nf
\fC
launcher=path_to_launcher(s)

\fR
.fi
.RE

A launcher is a freedesktop.org's \fC.desktop\fR file used to launch an
application. It usually includes a name, executable, comment (tooltip) and
icon.  System desktop files can be located in /usr/share/applications, and
/usr/local/share/applications. User's application files can be located in
~/.local/share/applications, or any other directory.

If \fCpath_to_launcher\fR is the path of a .desktop file, it will be used to create
a menu entry, unless an exclusion case applies (see section \fILauncher Exclusion
Cases\fR).

Any preceding \fCformat=format_string\fR line will apply to that entry.

Any preceding \fClauncherargs=arguments\fR line will apply to that entry, that is,
the \fCarguments\fR string will be appended to the command entry for the shell to
execute. Quote \fCarguments\fR as needed.

If \fCpath_to_launcher(s)\fR is a directory path (dirpath), it will be scanned for
.desktop files, which will all be used to create successive menu entries.

Any preceding \fClauncherdirfile=launcher_dirfile\fR line will apply to the menu
entry of each scanned dirpath.

\fCpath_to_launcher(s)\fR can also be a colon-separated list of paths. In this case
a single \fClauncher=\fR line effectively expands to multiple
\fClauncher=member_path\fR lines, where \fCmember_path\fR represents each successive
member of \fCpath_to_launcher(s)\fR.  Expansion stops at the end of the list if
\fCconfigure=nolauncherlistfirst\fR is enabled (by default it is). If
\fCconfigure=launcherlistfirst\fR is enabled, expansion stops after the first
successful file hit in the list.

Note that each unsuccessful expansion is likely to produce a "File not found"
error message, which in turn will display an error box. To prevent such error
box from appearing use \fCconfigure=errorconsoleonly\fR.

\fCpath_to_launcher(s)\fR follows the rules for paths referred to in menu
configuration files (see above):
.RS
.IP \[bu] 3
It can begin with a tilde, which will be expanded as in bash to $HOME.
.IP \[bu] 3
It can be absolute.
.IP \[bu] 3
Or it can be relative.  If \fCpath_to_launcher(s)\fR doesn't begin with a dot,
and the most recent \fClauncherdirectory=path_to_launcher_directory\fR line has a
non-null \fCpath_to_launcher_directory\fR, it's relative to that.
.IP \[bu] 3
Otherwise a relative \fCpath_to_launcher(s)\fR is relative to the path in which
the configuration file was found (as specified on the gtkmenuplus command
line, unless gtkmenuplus is reading from stdin).
.RE

If you want to refer to all the .desktop files in the directory specified by
\fClauncherdirectory=\fR use
.RS
.nf
\fC
launcher=.

\fR
.fi
.RE

or
.RS
.nf
\fC
launcher=*

\fR
.fi
.RE
.SS
Launcher Exclusion Cases

A .desktop file is displayed in the menu unless one or more of the following
exclusion cases apply:
.RS
.IP \[bu] 3
The file is a regular file and its name doesn't end with ".desktop", i.e.,
/path/MyEditor.desktop is included; /path/MyEditor is exluded.
.IP \[bu] 3
The file is a link and the name of its ultimate target doesn't end with
".desktop", i.e.,/path/MyEditor -> /path/a -> /path/b/geany.desktop   # included
/path/MyEditor -> /path/edit_app                     # excluded
.IP \[bu] 3
The file includes entry "NoDisplay=true" and \fCconfigure=launchernodisplay\fR is
enabled (by default it is).
.IP \[bu] 3
The file includes a "Categories=List" entry and List isn't empty, and an
applicable \fClauncherdirfile=\fR \fCCategories=\fR entry excludes List.
.IP \[bu] 3
The file doesn't include a "Category=List" entry or List is empty, and
\fCconfigure=launchernullcategory\fR is disabled (by default it's enabled), and a
"Category=" list of an applicable \fClauncherdirfile=\fR \fCdirfile\fR doesn't
include special category "NULL" (verbatim).
.IP \[bu] 3
The "Category=" entries of the .desktop file and of an applicable
\fClauncherdir=\fR \fCdirfile\fR are defined, and the intersection between their
list values is empty. Note that null list elements, such as the null item
found between two semicolons in e.g. "Desktop;;System", don't count towards
finding an intersection.
.RE
.SS
Launchersub
.RS
.nf
\fC
launchersub=path_to_directory

\fR
.fi
.RE

It is a recursive version of \fClauncher=\fR. It displays all the .desktop files
that it can find in \fCpath_to_directory\fR and in the subdirectories under it.
Menu entries are created in nested submenus according to the subdirectory
level. More information follows further down in this section.

\fCpath_to_directory\fR can also be a colon-separated list of paths. In this case a
single \fClaunchersub=\fR line effectively expands into multiple
\fClaunchersub=member_path\fR lines, where \fCmember_path\fR represents each successive
member of \fCpath_to_directory\fR.  Expansion stops at the end of the list if
\fCconfigure=nolauncherlistfirst\fR is enabled (by default it is). If
\fCconfigure=launcherlistfirst\fR is enabled, expansion stops after the first
successful recursive directory hit in the list.

Note that each unsuccessful expansion is likely to produce a "File not found"
error message, which in turn will display an error box. To prevent such error
box from appearing use \fCconfigure=errorconsoleonly\fR.

Rules for relative paths, the directives \fClauncherdirfile=\fR and \fClauncherargs=\fR,
and \fILauncher Exclusion Cases\fR all apply to \fClaunchersub=\fR as they do to
\fClauncher=\fR. Each topic is explained elsewhere in this document.

When \fClaunchersub=dirpath\fR is encounted submenus are created automatically for
\fCdirpath\fR and each scanned subdirectory.

Up to 5 menu levels are automatically nested (see \fCMAX_SUBMENU_DEPTH\fR).

By default the submenu label is the name of the subdirectory that includes its
.desktop files, and the submenu icon is undefined. To specify different values
and other properties use directive \fClauncherdirfile=\fR.

If the maximum allowed submenu depth is exceeded, \fClaunchersub=dirpath\fR reports
a warning and displays the menu. Contrast that with the \fCsubmenu=\fR directive,
which exits with a fatal error if submenu depth is exceeded.

By default subdirectory scanning depth is set to fill at most 5 submenu levels.
If launcher files exist in lower subdirectories they will be ignored without
warnings.

For menu testing purposes you can force printing warnings by telling
gtkmenuplus to scan for launcher files at deeper levels. Then if such files
exist and they can't be displayed within the \fCMAX_SUBMENU_DEPTH\fR hard limit, a
warning message is printed to the console. To increase the scan depth set
environment variable \fCGTKMENUPLUS_SCAN_DEPTH=5\fR or higher.

Item formatting for the items in \fCdirpath\fR of \fClaunchersub=dirpath\fR is set by
the most recent \fCformat=\fR and \fCtooltipformat=\fR directives that precede
\fClaunchersub=dirpath\fR. For nested subdirectories, you can control item
formatting by specifying \fCformat_strings\fR in a file named \fC.desktop.directory\fR.
See section \fIFormat\fR about \fCformat_strings\fR. Several example menus are included
in directory "test" of the project repository.
.SS
Launcherdirfile
.RS
.nf
\fC
launcherdirfile=launcher_dirfile

\fR
.fi
.RE

After this line is encountered, properties of \fCdirpath\fR in all subsequent
\fClauncher=dirpath\fR and \fClaunchersub=dirpath\fR lines are read from
\fClauncher_dirfile\fR, which stands of "launcher desktop directory file".

A \fClauncher_dirfile\fR is a .desktop file that doesn't include an "Exec=" line,
and may include lines "Type=Directory" and "Format=formatting".

It sets the menu entry label, icon, and tooltip for each scanned \fCdirpath\fR.

Formatting is applied to all contained items and cascades to subdirectories of
\fCdirpath\fR.

.desktop file entry "Categories=List", if any, is used to filter which .desktop
files to display in the menu, as explained in section \fILauncher Exclusion
Cases\fR.

\fClauncherdirfile=\fR followed by no text clears out the \fClauncher_dirpath\fR string
for all subsequent \fClauncher=dirpath\fR lines.

There can be multiple \fClauncherdirfiles\fR lines; each one sets the
\fClauncher_dirfile\fR for all \fClauncher=dirpath\fR lines that follow, until the next
\fClauncherdirfile=\fR line.

\fClauncher_dirfile\fR follows the rules for paths referred to in menu
configuration files (see above): tilde expansion and relative paths.

An alternative method to provide settings for \fClauncher{sub}=dirpath\fR lines is
to place a hidden file named \fC.desktop.directory\fR in each subdirectory. If this
file exists, it overrides the \fClauncher_dirfile\fR specified by
\fClauncherdirfile=launcher_dirfile\fR.

Example of \fClauncher_dirfile\fR:
.RS
.nf
\fC
# Note: This file is ignored if its dirpath is used in "launcher=dirpath".
[Desktop Entry]
Encoding=UTF\-8
Name=submenu label
Comment=redirected from .desktop.directory (tooltip)
Name[es]=localized label example
Comment[es]=localized tooltip example
Icon=icon_name_no_extension or full_path_to_icon_file_with_extension
Type=Directory
Categories=
# Format applies to contained items, and cascades.
Format=background="purple" etc.
# You can also apply direct (local) formatting to Name= and Comment=
# (label and tooltip), i.e.
# Name=<span>background="green">submenu name</span>

\fR
.fi
.RE
.SS
Launchersubmenu
.RS
.nf
\fC
launchersubmenu=launcher_dirfile

\fR
.fi
.RE

\fClaunchersubmenu=\fR describes a submenu as an alternative to \fCsubmenu=\fR.

Label, icon, and tooltip are read from \fClauncher_dirfile\fR instead of being
specified through \fCitem=\fR, \fCicon=\fR, etc.  In all other aspects
\fClaunchersubmenu\fR works like \fCsubmenu=\fR.
.SS
Launcherargs
.RS
.nf
\fC
launcherargs=arguments

\fR
.fi
.RE

After this line is encountered, in all subsequent \fClauncher{sub}=\fR lines, the
\fCarguments\fR string will be appended to the launcher command entry for the shell
to execute. Quote \fCarguments\fR as needed.

\fClauncherargs=\fR followed by no text clears out the arguments string for all
subsequent \fClauncher=\fR lines.

There can be multiple \fClauncherargs\fR lines; each one sets the arguments for all
\fClauncher{sub}=\fR lines that follow, until the next \fClauncherargs=\fR line.
.SS
Launcherdir, Launcherdirectory
.RS
.nf
\fC
launcherdirectory=path_to_launcher_directory

launcherdir=path_to_launcher_directory

\fR
.fi
.RE

After this line is encountered, in all subsequent
\fClauncher=path_to_launcher(s)\fR lines, if \fCpath_to_launcher(s)\fR  doesn't begin
with a tilde or forward slash, it's assumed to be relative to
\fCpath_to_launcher_directory\fR.

\fCpath_to_launcher_directory\fR follows the rules for paths referred to in menu
configuration files (see above).

If \fCpath_to_launcher_directory\fR doesn't begin with a tilde or forward slash,
it's assumed to be relative to the path in which the configuration file was
found (as specified on command line).

\fClauncherdirectory=\fR followed by no text reverts the base path for icons to the
path in which the configuration file was found (as specified on command line).

There can be multiple \fClauncherdirectory\fR lines; each one sets the base
directory for all \fClauncher=\fR that follow, until the next \fClauncherdirectory=\fR
line.
.SS
Activationlogfile
.RS
.nf
\fC
activationlogfile=logfile_path

\fR
.fi
.RE

After this line is encountered and \fClogfile_path\fR specifies a valid file path,
three things happen:
.RS
.IP "{current_li}." 3
File \fClogfile_path\fR is created if it doesn't exist.
.IP "{current_li}." 3
All parsed menu items and launchers encountered after this line and before
an \fCactivationlogfile=\fR (null path) line are flagged as "loggable".
.IP "{current_li}." 3
Activating a "loggable" entry writes its attributes (\fCitem=\fR, \fCcmd=\fR,
\fCicon=\fR, \fCtooltip=\fR or, for launchers, "Name=", "Exec=", "Icon=",
"Comment=") to the log file \fClogfile_path\fR.
.RE

The log file is formatted as a gtkmenuplus \fCmenu_configuration_file\fR and can be
included in other menu configuration files with \fCinclude=logfile_path\fR.

If \fClogfile_path\fR doesn't begin with a tilde or forward slash, it's assumed to
be relative to the path in which the configuration file was found (as specified
on command line).

Generally speaking the log file shouldn't be edited, although some changes are
allowed within the limits explained in the project repository (see git commit
message 8bd8abf, which documents log file format and application development
policies).
.SS
Include

First form:
.RS
.nf
\fC
include=menu_configuration_file [parameter1 [parameter2 ...]]

\fR
.fi
.RE

Second form (explained further down):
.RS
.nf
\fC
include=path_to_directory[/file_glob] [directory_glob] 

\fR
.fi
.RE

The first form inserts the contents of a \fCmenu_configuration_file\fR into the one
in which the line occurs, at the point at which it occurs.

\fCmenu_configuration_file\fR follows the rules for paths referred to in menu
configuration files (see above).

If you want the contents of a \fCmenu_configuration_file\fR to appear in a submenu,
indent the \fCinclude=\fR line as well as all the lines of the
\fCmenu_configuration_file\fR just as you would if the contents of the file were
found in the including file.

Be careful not to include recursively, directly or indirectly, a
\fCmenu_configuration_file\fR in itself.

Parameters can be referred to as \fC$1\fR, \fC$2\fR, etc. anywhere in the included
\fCmenu_configuration_file\fR.  See section \fIParameter references\fR above for more
detail.

The following rules apply as the included \fCmenu_configuration_file\fR is
processed:

Any paths (see section \fIPaths\fR above) beginning with a dot are taken to be
relative to the directory in which the included file lives; this will of course
change nothing if the including and included file are in the same directory.

If \fCicondirectory=path_to_icon_directory\fR and/or
\fClauncherdirectory=path_to_launcher_directory\fR directives are in force in the
including file, the \fCpath_to_icon_directory\fR or \fCpath_to_launcher_directory\fR
remain in force within the included file.

If \fCicondirectory=path_to_icon_directory\fR and/or
\fClauncherdirectory=path_to_launcher_directory\fR lines are encountered in an
included file, the \fCpath_to_icon_directory\fR or \fCpath_to_launcher_directory\fR
remain in force only within the included file; they revert to the values set in
the including file once the included file is processed.

If the most recently encountered \fCconfigure=\fR line in the menu configuration
file included the word \fCformattinglocal\fR, the effects of any \fCformat=\fR or
\fCtooltipformat=\fR lines that occur within the included menu configuration file
will persist only until the end of that included file.  Formatting then reverts
to that specified by the last encountered \fCformat=\fR and \fCtooltipformat=\fR lines
in the including file.

This behaviour can be turned off with a \fCconfigure=\fR line containing the word
\fCformattinglocal\fR.

Second form:
.RS
.nf
\fC
include=path_to_directory[/file_glob] [directory_glob] 

\fR
.fi
.RE

\fCpath_to_directory\fR follows the rules for paths referred to in menu
configuration files.

The second form inserts a series of menu entries, one per file, including only
those files to which the user has read access matching the \fCfile_glob\fR
specified (e.g. \fC*.txt\fR, \fCd?t*\fR, \fC[a-f]*.txt\fR).


(??) Extended globbing patterns can be used: see

http://www.linuxjournal.com/content/bash-extended-globbing

The generated menu item name will be the file name; if chosen the command
executed will be the full path to the file.

There is no recursion into subdirectories under \fCpath_to_directory\fR unless
there's a \fCdirectory_glob\fR.  If one exists it's applied only to subdirectories
within \fCpath_to_directory\fR, not to the matching of subdirectories further down
the directory tree.

Only subdirectories containing a file matching \fCfile_glob\fR appear in the
generated menu.  Subdirectories to which the user doesn't have read access are
ignored.

The second form may be immediately followed by any or all of \fCicon=\fR,
\fCtooltip=\fR and \fCcmd=\fR lines, in any order.  If it is, the icon and tooltip will
be applied to each of the menu entries created; if there's a command, it will
be prepended to the path associated with the chosen item in the menu generated
by the \fCinclude=\fR line.
.SS
Absolute Path
.RS
.nf
\fC
/path_to/file, ~/path_to/file

\fR
.fi
.RE

A line in a menu configuration file can be an absolute path to a file,
beginning with a forward slash or tilde.  No directive is expected or required,
nor is it to be followed by \fCicon=\fR, \fCtooltip=\fR or \fCcmd=\fR lines.


By default, menu items generated from such lines will display the file name
prefixed by its immediately containing subdirectory.

Each generated item's tooltip will display the full path to the file, as
provided in the menu configuration file, before tilde expansion.

If a previously encountered \fCconfigure=\fR line includes \fCabspathparts n\fR, the
lowest n elements of the path (the filename counts as one element) will be
displayed.  If \fCn\fR is zero, the whole path will be displayed.

The most likely use of such lines in a menu configuration file is to make it
possible to generate a configuration file on the fly and pipe it into
gtkmenuplus, with e.g. something like:
.RS
.nf
\fC
{ echo "configure abspathparts 3" ; find ~ \-name *.conf } | gtkmenuplus \-

\fR
.fi
.RE
.SS
Submenu
.RS
.nf
\fC
submenu=submenu_description

\fR
.fi
.RE

It denotes a \fCsubmenu_description\fR to show in the menu listing. See also
\fClaunchersubmenu=\fR.

It may be followed by \fCicon=\fR and/or \fCtooltip=\fR lines, which, if they are to
relate to a given \fCsubmenu=\fR, must precede lines with any other directive except
\fCif=\fR, \fCelseif=\fR, \fCelse\fR or \fCendif\fR.

By default, (but see \fCconfigure=endsubmenu\fR, below):
.RS
.IP \[bu] 3
The \fCicon=\fR and/or \fCtooltip=\fR must be indented using the tab character.  They
must be indented by one more tabs than the \fCsubmenu=\fR line, as must all menu
entries in the submenu.
.IP \[bu] 3
The first line that is not indented with the same number of tabs signals the
end of this submenu.
.IP \[bu] 3
The indentation of lines with directives like \fCiconsize=\fR, \fCmenupos=\fR,
\fCicondirectory=\fR, \fCformat=\fR, \fCtooltipformat=\fR, \fCif=\fR, etc, don't make up part
of the definition of a menu item or submenu definition, and therefore is
ignored and has no effect on when a submenu ends.
.RE

Submenus can be nested up to a maximum of 5 levels. Changing this limit
requires recompiling the source code: look for and change the value of
\fCMAX_SUBMENU_DEPTH\fR.

A \fCsubmenu=\fR line marks the end of any menu item or submenu that precede it.
.SS
Configure
.RS
.nf
\fC
configure= keywords

\fR
.fi
.RE

Any of the keywords \fCendsubmenu\fR, \fCnoendsubmenu\fR, \fCicons\fR, \fCnoicons\fR,
\fCformattinglocal\fR, \fCnoformattinglocal\fR, \fClaunchernodisplay\fR,
\fCnolaunchernodisplay\fR, \fClaunchernullcategory\fR, \fCnolaunchernullcategory\fR,
\fClauncherlistfirst\fR, \fCnolauncherlistfirst\fR, \fCerrormsgbox\fR , \fCnoerrormsgbox\fR,
\fCabspathparts\fR, \fCmenuposition\fR, and \fCiconsize\fR can occur on this line.


\fCabspathparts\fR and \fCiconsize\fR must be immediately followed by whitespace, then
an integer; \fCmenuposition\fR must be followed by whitespace, then two
whitespace-separated integers.

For the effects of \fCendsubmenu\fR/\fCnoendsubmenu\fR, see the \fCendsubmenu\fR line.

For the effects of \fCicons\fR/\fCnoicons\fR, see the \fCicon=\fR line.

For the effects of \fCformattinglocal\fR/\fCnoformattinglocal\fR, see the
\fCinclude=menu_configuration_file\fR line.

For the effects of \fClaunchernodisplay\fR/\fCnolaunchernodisplay\fR and
\fClaunchernullcategory\fR / \fCnolaunchernullcategory\fR, see \fILauncher Exclusion
Cases\fR in section \fILauncher\fR, which also applies to the \fClaunchersub=\fR line.

For the effects of \fClauncherlistfirst\fR/\fCnolauncherlistfirst\fR see the
\fClauncher=\fR and \fClaunchersub=\fR lines.

For the effects of \fCabspathparts n\fR, see section \fIPlain File Path\fR.

\fCmenuposition x y\fR has the same effect as the \fCmenuposition=x y\fR line.  Only
one x y menu position, specified by either method, may occur in a menu
configuration file.

\fCiconsize n\fR has the same effect as the \fCiconsize=size\fR line, overrides the
effect of that line, and is overridden by any such following line.

By default when gtkmenuplus is \fInot\fR launched via a CLI, fatal errors are
displayed in a message box.  \fCerrorconsoleonly\fR prevents such message boxes
from appearing. \fCnoerrorconsoleonly\fR reverts to the default behaviour.
.SS
Onexit
.RS
.nf
\fC
onexit=command

\fR
.fi
.RE

Shell command \fCcommand\fR is executed after the menu gets deactivated.  onexit is
a hook for a menu script to clean up after the menu ends.

A script can include \fConexit=command\fR multiple times.  Only the last \fCcommand\fR
will be executed. Use \fConexit=\fR to clear an established \fCcommand\fR.

If you need to run multiple shell commands, wrap them in a "sh -c" invocation.
Note that \fCcommand\fR is executed regardless of a menu entry being selected, and
it isn't synchronized with the execution/termination of an item or launcher.
.SS
Endsubmenu
.RS
.nf
\fC
endsubmenu

\fR
.fi
.RE

Once \fCendsubmenu\fR is encountered on a \fCconfigure=\fR line, indentation of lines
no longer signals which menu entries belong to which submenu.  Instead
indentation is ignored, and everything after a \fCsubmenu=\fR line belongs to that
submenu until the occurrence of an \fCendsubmenu\fR line.  Behaviour reverts to
default when \fCnoendsubmenu\fR occurs on a subsequent \fCconfigure=\fR line.

Ignoring indentation means that leading whitespace can be used cosmetically,
e.g.  to mark lines within \fCif=\fR/\fCelseif=\fR/\fCelse\fR/\fCendif\fR blocks (and of course
to continue to clarify what belongs to which submenu).
.SS
Separator
.RS
.nf
\fC
separator

\fR
.fi
.RE

It displays a line in the menu.

A separator marks the end of any menu item or submenu preceding it.
.SS
Iconsize
.RS
.nf
\fC
iconsize=size

\fR
.fi
.RE

An optional line that changes the dimensions of the image used for succeeding
menu items.  There can be multiple \fCiconsize=\fR lines; each one sets the icon
size for all menu entries that follow, until the next \fCiconsize=\fR line.

Size must be between 20 and 200.

Standard icons are typically 16, 24, 48 or 96 pixels square.

If no \fCiconsize=\fR is in force size will be 30 unless the gtk framework returns
a different size.

To speed execution, all icon files associated with a menu configuration file
should be of the image size specified by the most recent \fCiconsize=\fR line.

An \fCiconsize=\fR line marks the end of any menu item or submenu preceding it.

You can get the same result by putting \fCiconsize size\fR on a \fCconfigure=\fR line.
.SS
Menupos, Menuposition
.RS
.nf
\fC
menupos=x y

menuposition=x y

\fR
.fi
.RE

An optional line to force the menu to open at a given x-y position (the program
xev can help you find coordinates - see its man page).  If no \fCmenupos=\fR in
encountered, the menu is shown at the mouse cursor position.  Only one
\fCmenupos=\fR is allowed per configuration file.

An \fCmenupos=\fR line marks the end of any menu item or submenu preceding it.

You can get the same result by putting \fCmenuposition x y\fR on a \fCconfigure=\fR
line.
.SS
Icondirectory
.RS
.nf
\fC
icondirectory=path_to_icon_directory

\fR
.fi
.RE

After this line is encountered, in all subsequent \fCicon=path_to_image_file\fR
lines, if \fCpath_to_image_file\fR, doesn't begin with a tilde or forward slash
it's assumed to be relative to  \fCpath_to_icon_directory\fR.

\fCpath_to_icon_directory\fR follows the rules for paths referred to in menu
configuration files (see above).

\fCicondirectory=\fR followed by no text reverts the base path for icons to the
path in which the configuration file was found (as specified on command line).

There can be multiple \fCicondirectory=\fR lines; each one sets the icon directory
for all menu entries that follow, until the next \fCicondirectory=\fR line.

An \fCicondirectory=\fR line marks the end of any menu item or submenu preceding
it.
.SS
If, Elseif, Else, Endif, Fi
.RS
.nf
\fC
if=condition
elseif=condition or elif=condition
else
endif or fi

\fR
.fi
.RE

\fCcondition\fR may be either
.RS
.IP \[bu] 3
A reference to an argument following the menu configuration file on the
command line when gtkmenuplus was called, the arguments referred to by the
reference \fC$1\fR, \fC$2\fR,... etc, e.g.if= $2  # referring to the third argument on the gtkmenuplus command line
.IP \[bu] 3
A valid command that the shell can execute that produces a value on \fCstdout\fR.
.IP \[bu] 3
A variable previously defined by a previous \fCvar=\fR line in the menu
configuration file.
.RE

In either case the value is expected to be an integer, "yes", "true", "no" or
"false", all case insensitive.

If the value (either the result of command execution sent to \fCstdout\fR or
received as a parameter) is non-zero, "true" or "yes", the menu entries
following the \fCif=\fR up to the following \fCelse\fR or \fCendif\fR will be displayed.

If that value is zero, "false" or "no" , the menu entries following the \fCif=\fR
up to the following \fCelse\fR or \fCendif\fR will \fInot\fR be displayed, but any after a
following \fCelse\fR line will be.

An \fCif=/[elseif=]/[else]endif\fR block can be embedded within another.

If \fCif=$n\fR or \fCelseif=$n\fR lines are read when there are less than \fCn\fR
parameters on the gtkmenuplus command line, all lines from the line up to the
matching \fCelseif\fR or \fCendif\fR will be processed into the menu.

If you want to test some condition requiring a call to the shell, and you want
to use the same condition in various \fCif=\fR lines in your menu configuration
file, you might be best to invoke the shell command within an argument on the
command line; that way the shell needs to be invoked only once, instead of
multiple times for multiple \fCif=\fR statements.

\fCif=\fR, \fCelseif=\fR, \fCelse\fR and \fCendif\fR lines do \fInot\fR mark the end of any menu
item or submenu preceding it.  So you can have \fCtooltip=\fR or \fCicon=\fR lines
apply to any of several \fCitem=\fRs that might appear conditionally before them
e.g.
.RS
.nf
\fC
if= [ `date +%H` \-lt 18 ]; printf $?  # if past 18:00 hours
  item = evening game
  cmd = mahjongg
else
 item = daytime game
 cmd = mines
endif
tooltip = the item you see here depends on the time of day
icon=games_package.png

\fR
.fi
.RE

\fCif=\fR, \fCelseif=\fR, \fCelse\fR and \fCendif\fR lines are scoped to each menu
configuration file.  If you \fCinclude=\fR a menu configuration file, an \fCendif\fR
line must follow an \fCif=\fR line within that file, and won't relate to a \fCif=\fR
line  in the including file.

\fCerror=message\fR can be used to stop menu configuration file processing, the
need for which would generally be detected by \fCif=\fR, \fCelseif=\fR, \fCelse\fR and
\fCendif\fR lines.

Sample conditions in \fCif=condition\fR, \fCelseif=condition\fR or command line
parameters:

Show menu entries following the if= line only in PM hours:
.RS
.nf
\fC
if= ! [ `date +%p` = 'PM' ]; printf $?

\fR
.fi
.RE

On the command line:
.RS
.nf
\fC
gtkmenuplus path_to_configuration_file "! [ `date +%p` = 'PM' ]; printf $?"

\fR
.fi
.RE

and then use \fCif= $1\fR inside the configuration file.

The date command can be used to show menu items on certain days of week, days
of the month, week of the year, etc.

Show menu entries following the \fCif=\fR line only if using a particular physical
screen:
.RS
.nf
\fC
if= xrandr \-\-current | grep "VGA\-0 connected" | wc \-l

\fR
.fi
.RE

Show menu entries following the \fCif=\fR line only if firefox is running:
.RS
.nf
\fC
if= xdotool search \-\-name Firefox  | wc \-l

\fR
.fi
.RE

Test if a particular memory stick is mounted:
.RS
.nf
\fC
if= ! [ \-d '/media/VOL_LABEL'  ]; printf $?

\fR
.fi
.RE

Test if the partition \fC$HOME\fR resides on is more than 90% full:
.RS
.nf
\fC
if=  df $HOME | awk 'NR==2{split($5,A,/%/);print (A[1]+0>90)}'

\fR
.fi
.RE
.SH BUGS

Please report defects in the \fIIssues\fR page of the gtkmenuplus project home.
.SH AUTHOR

copyright (C) 2013 Alan Campbell, (C) 2016-2018 step

step is the current maintainer.

\fBAcknowledgements\fR

Thanks to John Vorthman for providing myGtkMenu code.

The idea of importing .desktop files was borrowed from popdown
.SH SEE ALSO

gtkmenuplus(1) - usage

Gtkmenuplus home page and project repository (current version):

https://github.com/step-/gtkmenuplus

Gtkmenuplus 1.0 home page (old version):

https://sites.google.com/site/entropyreduction/gtkmenuplus

myGtkMenu home page (old version):

https://sites.google.com/site/jvinla/home

Popdown home page:

http://www.manatlan.com/page/popdown

