.TH gtkmenuplus 1 "2018-09-16" "version 1.1.8" usage
.SH NAME

gtkmenuplus - display GTK menus from text files
.SH SYNOPSIS
.RS
.nf
\fC
gtkmenuplus [options] [menu_configuration_file] [parameter ...]

gtkmenuplus [options] directive[;directive...] [parameter ...]

\fR
.fi
.RE
.SH DESCRIPTION

Gtkmenuplus reads a menu description from configuration directives in a text
file or stdin, and displays the resulting graphical menu. It can be used to
open documents and run applications and scripts.  Menus can be nested. Menu
items comprising label, icon and tooltip, can be formatted each one
independently.

Gtkmenuplus has its own, simple scripting language, with conditionals,
variables, and shell integration, which allow creating dynamic menu entries.

It can read freedesktop.org's .desktop application files, automatically
scanning and displaying entire folder hierarchies with a single command.

Gtkmenuplus is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License, version 2, as published by the
Free Software Foundation. Gtkmenuplus comes with ABSOLUTELY NO WARRANTY.

See the file COPYING distributed with gtkmenuplus source code for the complete
license.

Gtkmenuplus was forked from myGtkMenu.
.SH OPTIONS

-c, --gather-comments
.RS

Try specifying \fC-c\fR if you are having compatibility issues with a menu
description file designed for a very old version of gtkmenuplus or for
myGtkMenu. Option \fC-c\fR disables support for very long comment lines.
.RE

-i, --info
.RS

Print more informational messages to \fCstdout\fR and \fCstderr\fR. Repeat \fC-i\fR to
increase verbosity.
.RE

-h, --help
.RS

Print a help message to \fCstdout\fR or to a graphical window and exit.
.RE

-q, --quiet
.RS

Do not print statistics and informational messages to \fCstdout\fR.
.RE

-v, --version
.RS

Print version string to \fCstdout\fR and exit.
.RE

--
.RS

Stop recognizing options. All words after \fC--\fR are regarded as
\fCmenu_configuration file\fR and \fCparameter\fRs or as \fCconfiguration_line\fRs.
.RE
.SH ARGUMENTS

Without arguments, gtkmenuplus will attempt to read file \fCtest_menu.txt\fR found
in the same directory as gtkmenuplus.  Otherwise the following are the possible
arguments and their descriptions.
.RS
.nf
\fC
configuration_file
\-
directive[;directive...]
parameter [parameter ...]

\fR
.fi
.RE

The \fCconfiguration_file\fR is a text file that describes the menu according to
the format and \fCdirective\fRs specified in gtkmenuplus(5).

Use \fC-\fR to read the menu description from \fCstdin\fR. In this case, any relative
path references are taken as relative to \fC$HOME\fR.

Or you can pass configuration directives directly on the command line. Put
semicolons between configuration directives and wrap the entire string with
single quotes.

You can invoke gtkmenuplus with additional \fCparameter\fRs.  If you do, their
values can be referred to in any line of your menu configuration file as \fC$1\fR
for the first parameter beyond \fCmenu_configuration_file\fR, \fC$2\fR for the second,
and so on. \fC$0\fR refers to the path to \fCmenu_configuration_file\fR.

If \fC$\fR isn't followed by an integer or a variable name it's treated as literal
text.

If you provide a parameter but never reference it in the menu configuration
file, gtkmenuplus will print a warning to the terminal window.
.SH EXAMPLES
.RS
.nf
\fC
gtkmenuplus 'include=~/bin/*.sh ; cmd=geany; icon=NULL'        

gtkmenuplus $'submenu=var/run;\tinclude=/var/run/* *'

gtkmenuplus launchersub=/usr/share/applications

\fR
.fi
.RE

Try appending
.RS
.nf
\fC
;/usr/local/share/applications;~/.local/share/applications

\fR
.fi
.RE

to the last command if those directories are populated in your system.

For more examples see gtkmenuplus(5) and visit the gtkmenuplus project home
page (\fC->\fRSEE ALSO).
.SH EXIT STATUS

Gtkmenuplus exits 0 on success, and >0 if an error occurs.
.SH BUGS

Please report defects in the \fIIssues\fR page of the gtkmenuplus project home.

To troubleshoot your menu configuration files run gtkmenuplus from the shell
prompt.  When in doubt, enter the complete pathname of the files:
.RS
.nf
\fC
/path/to/gtkmenuplus /path/to/menu_configuration_file

\fR
.fi
.RE

At the shell prompt gtkmenuplus will produce status and error messages,
including reports of errors or problems with the configuration file.
.SH AUTHORS

copyright (C) 2013 Alan Campbell, (C) 2016-2018 step

step is the current maintainer.

\fBAcknowledgements\fR

Thanks to John Vorthman for providing myGtkMenu code.

The idea of importing .desktop files was borrowed from popdown.
.SH SEE ALSO

gtkmenuplus(5) - menu configuration file description

Gtkmenuplus home page and project repository (current version):

https://github.com/step-/gtkmenuplus

Gtkmenuplus 1.0 home page (old version):

https://sites.google.com/site/entropyreduction/gtkmenuplus

myGtkMenu home page (old version):

https://sites.google.com/site/jvinla/home

Popdown home page:

http://www.manatlan.com/page/popdown

